# training arguments - SFTConfig or TrainingArguments
training_args:
  dataset_text_field: null
  learning_rate: 1e-6
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 2
  eval_accumulation_steps: 8
  gradient_accumulation_steps: 32
  output_dir: null  # provided by pipeline orchestration at runtime
  logging_steps: 1
  num_train_epochs: 3
  max_steps: -1
  report_to: "wandb"
  seed: 0
  do_eval: True
  eval_strategy: "steps"
  eval_steps: 100
  include_inputs_for_metrics: True
  load_best_model_at_end: True
  batch_eval_metrics: True
  predict_with_generate: True
  generation_max_length: 256
  generation_num_beams: 1
  save_total_limit: 1
  # remove_unused_columns: False

generation_config:  # use greedy decoding during evaluation
  max_new_tokens: 256
  num_beams: 1
  do_sample: False
  num_return_sequences: 1

model_config:
  model_name_or_path: "EleutherAI/pythia-2.8b"
  attn_implementation: "eager"

# data
data_fp: null  # provided by pipeline orchestration at runtime
train_size: 0.99
max_eval_size: 200 # evaluation takes a long time, so we set a max. size on the eval dataset
seq_length: 512
format_type: "plain_pairs"

# test function
test_fn_type: "ehrlich"  # [ehrlich, mt_fuji
test_fn_fp: null  # provided by pipeline orchestration at runtime

# instrumentation
sanity_check: False  # If true, will train on only 1K examples and not save the final model.
log_level: "info"
wandb_host: null
wandb_mode: "online"
project_name: "finetune_ehrlich"
exp_name: "finetune_pythia-2.8b"
job_name: null
__version__: null

# other
s3_output_dir: null  # provided by pipeline orchestration at runtime